### ISSUE TITLE
Panic executing the binary

### ISSUE THREAD

**Issue by toonketels** [NoUseFreak/sawsh#7]
Executing the provided binary result in a panic. Seems you're filesystem is expected.

➜  ~ sawsh
panic: runtime error: index out of range

goroutine 1 [running]:
main.main()
        /Users/dries/Projects/Personal/awsh/sawsh.go:21 +0x335

**Comment by NoUseFreak** [comment]
Is this still an issue in the latest version? Make sure to log the version or date when you downloaded the binary.

**Comment by NoUseFreak** [comment]
Should be fixed.
